workflows:
  ios-release:
    name: MotivateMe iOS Release
    max_build_duration: 60
    integrations:
      app_store_connect: codemagic
    environment:
      vars:
        BUNDLE_ID: com.ayoub.motivateMe
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "$BUNDLE_ID" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles
      - name: Build ipa
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - ayoubboutglay318@gmail.com
